/*
Model: User Purchase Frequency

Purpose:
Create one row per purchaser and summarise purchase behaviour
across the analysis period.

The model calculates:
- Number of purchasing sessions per user
- Total revenue generated by each purchaser
- First purchase date
- Last purchase date
- Purchase-frequency segment

Purchase-frequency groups:
- 1 Purchase
- 2 Purchases
- 3+ Purchases

Input table:
ga4-marketing-analysis-509418.ga4_analysis.session_marketing_performance_final

Output table:
ga4-marketing-analysis-509418.ga4_analysis.user_purchase_frequency

Note:
Purchase frequency is based on distinct sessions containing a
purchase event rather than distinct transaction IDs.
*/


CREATE OR REPLACE TABLE
    `ga4-marketing-analysis-509418.ga4_analysis.user_purchase_frequency`
AS


-- ============================================================
-- 1. AGGREGATE PURCHASE BEHAVIOUR TO USER LEVEL
-- ============================================================

WITH purchaser_aggregation AS (

    SELECT
        user_pseudo_id,

        COUNT(DISTINCT unique_session_id)
            AS purchase_count,

        ROUND(
            SUM(session_revenue_usd),
            2
        ) AS total_revenue_usd,

        MIN(session_date)
            AS first_purchase_date,

        MAX(session_date)
            AS last_purchase_date

    FROM
        `ga4-marketing-analysis-509418.ga4_analysis.session_marketing_performance_final`

    WHERE purchase_flag = 1

    GROUP BY user_pseudo_id
)


-- ============================================================
-- 2. CLASSIFY PURCHASERS BY PURCHASE FREQUENCY
-- ============================================================

SELECT
    user_pseudo_id,
    purchase_count,
    total_revenue_usd,
    first_purchase_date,
    last_purchase_date,

    CASE
        WHEN purchase_count = 1
            THEN '1 Purchase'

        WHEN purchase_count = 2
            THEN '2 Purchases'

        WHEN purchase_count >= 3
            THEN '3+ Purchases'
    END AS frequency_group

FROM purchaser_aggregation;
